import { db, pg } from "./src/models/db.js";
import { organizations, repositories, ciRuns, users, platformUsage } from "./src/models/schema.js";
import { createLlmGatewayRoutes } from "./src/routes/llm-gateway.js";
import { setOrgLlmKey } from "./src/services/org-llm-key.js";
import { hashGatewayToken } from "./src/services/llm-gateway.js";
import { eq } from "drizzle-orm";
const REAL = process.env.OR_KEY!;
const [owner] = await db.insert(users).values({ email: `n3f-${Date.now()}@t.co`, username: `n3f${Date.now()}`, passwordHash: "x" }).returning();
const [org] = await db.insert(organizations).values({ name: `n3f-${Date.now()}`, ownerUserId: owner.id }).returning();
const [repo] = await db.insert(repositories).values({ name: `n3fr-${Date.now()}`, namespaceType: "org", namespaceId: org.id, ownerUserId: owner.id }).returning();
const tok = `chgw_f_${Date.now()}`;
await db.insert(ciRuns).values({ repoId: repo.id, runnerToken: "rt", status: "running", origin: "agent", gatewayTokenHash: hashGatewayToken(tok) });
await setOrgLlmKey(db, org.id, "openai", REAL);
const gw = createLlmGatewayRoutes(db);
const res = await gw.request("/openai/v1/chat/completions", { method: "POST", headers: { authorization: `Bearer ${tok}`, "content-type": "application/json" }, body: JSON.stringify({ model: "z-ai/glm-5.2", messages: [{ role: "user", content: "reply OK" }], max_tokens: 8 }) });
const j = JSON.parse(await res.text());
console.log("LIVE status=" + res.status + " reply=" + JSON.stringify(j.choices?.[0]?.message?.content ?? j.error?.message ?? ""));
const usage = await db.select().from(platformUsage).where(eq(platformUsage.orgId, org.id));
console.log("LIVE metering rows=" + usage.length + " cost_micro=" + (usage[0]?.costMicroUsd ?? 0) + " keyOwner=" + ((usage[0]?.meta as any)?.keyOwner ?? "-"));
await db.delete(organizations).where(eq(organizations.id, org.id));
await db.delete(users).where(eq(users.id, owner.id));
await pg.end();
