package internal

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
)

// POST /internal/repos/init
//
// Creates a bare repo at `${GIT_REPOS_BASE_PATH}/${ns}/${name}.git` and installs
// the pre-receive hook. Idempotent — returns 200 if it already exists.
func (r *Router) handleInit(w http.ResponseWriter, req *http.Request) {
	var body Repo
	if err := json.NewDecoder(req.Body).Decode(&body); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "invalid_json"})
		return
	}
	if body.Namespace == "" || body.Name == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "namespace_and_name_required"})
		return
	}
	dir := body.Path(r.cfg.ReposBasePath)
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{"error": "mkdir: " + err.Error()})
			return
		}
		cmd := exec.Command("git", "init", "--bare", dir)
		if out, err := cmd.CombinedOutput(); err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{"error": fmt.Sprintf("git init: %v (%s)", err, string(out))})
			return
		}
	}
	if err := installPreReceiveHook(dir, r.cfg); err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"error": "hook_install: " + err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "path": dir})
}

// Writes a shell pre-receive hook that posts ref updates to the Node API's
// internal endpoint. The hook signs `{ts}.{sha256(body)}` with the shared
// secret and aborts the push if the API rejects with a non-2xx.
func installPreReceiveHook(repoDir string, cfg *Config) error {
	hookPath := filepath.Join(repoDir, "hooks", "pre-receive")
	if cfg.ApiBaseUrl == "" || cfg.InternalToken == "" {
		// No API to call back to (single-process dev mode). Skip — push still
		// works, just without the synchronous ref-log.
		return nil
	}
	content := fmt.Sprintf(`#!/bin/bash
set -euo pipefail

# Auto-generated by clawhub git-service. Writes ref updates to the API's
# Postgres-as-WAL before they apply locally. Rejects the push if the API errors.
API_URL=%q
TOKEN=%q
SHARD_ID=%q
REPO_NS=%q
REPO_NAME=%q

UPDATES_JSON='['
FIRST=1
while read -r OLD_SHA NEW_SHA REF; do
  if [ $FIRST -eq 0 ]; then UPDATES_JSON+=,; fi
  FIRST=0
  UPDATES_JSON+="{\"ref\":\"${REF}\",\"oldSha\":\"${OLD_SHA}\",\"newSha\":\"${NEW_SHA}\"}"
done
UPDATES_JSON+=']'

BODY=$(printf '{"namespace":"%%s","repo":"%%s","shardId":"%%s","updates":%%s}' "$REPO_NS" "$REPO_NAME" "$SHARD_ID" "$UPDATES_JSON")
TS=$(date +%%s)
DIGEST=$(printf '%%s' "$BODY" | openssl dgst -sha256 -hex | awk '{print $2}')
SIG=$(printf '%%s.%%s' "$TS" "$DIGEST" | openssl dgst -sha256 -hmac "$TOKEN" -hex | awk '{print $2}')

HTTP_STATUS=$(curl -s -o /tmp/clawhub_ref_log_response -w '%%{http_code}' \
  -X POST "$API_URL/api/v1/internal/ref-log" \
  -H "x-clawhub-ts: $TS" \
  -H "x-clawhub-sig: $SIG" \
  -H "content-type: application/json" \
  -d "$BODY" || echo "000")

if [ "$HTTP_STATUS" -lt 200 ] || [ "$HTTP_STATUS" -ge 300 ]; then
  echo "[clawhub] ref-log rejected the push (status $HTTP_STATUS):" >&2
  cat /tmp/clawhub_ref_log_response >&2 || true
  exit 1
fi

exit 0
`, cfg.ApiBaseUrl, cfg.InternalToken, cfg.ShardID, hookRepoNs(repoDir), hookRepoName(repoDir))

	if err := os.WriteFile(hookPath, []byte(content), 0o755); err != nil {
		return err
	}
	return nil
}

func hookRepoNs(repoDir string) string {
	parent := filepath.Dir(repoDir)
	return filepath.Base(parent)
}

func hookRepoName(repoDir string) string {
	base := filepath.Base(repoDir)
	return trimGitSuffix(base)
}

func trimGitSuffix(s string) string {
	const suf = ".git"
	if len(s) > len(suf) && s[len(s)-len(suf):] == suf {
		return s[:len(s)-len(suf)]
	}
	return s
}
